# Generated by Django 5.1.6 on 2025-02-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_category_difficultylevel_quiz_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('coding', 'Coding Question')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='user_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='user_code_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.choice'),
        ),
    ]
